import { Router } from 'express';
import { container } from 'tsyringe';
import { DanhMucController } from '../controllers/danhmucController';
const danhmucRouter = Router();
const danhmucController = container.resolve(DanhMucController);
danhmucRouter.get('/getbyid/:id', danhmucController.getDanhMucById.bind(danhmucController));
danhmucRouter.get('/get-all', danhmucController.getDanhMucAll.bind(danhmucController));
danhmucRouter.post('/update', danhmucController.updateDanhMuc.bind(danhmucController));
danhmucRouter.get('/delete/:id', danhmucController.deleteDanhMuc.bind(danhmucController));
danhmucRouter.post('/search', danhmucController.searchDanhMuc.bind(danhmucController));
export default danhmucRouter;